<?php
header('Content-Type: application/json; charset=utf-8');
?>
[
[
{
"comment_post_ID": "33441",
"comment_author": "Купибилет",
"comment_author_email": "pr@kupibilet.ru",
"comment_author_url": "",
"comment_author_IP": "185.76.9.105",
"comment_date": "2023-05-24 12:55:01",
"comment_date_gmt": "2023-05-24 09:55:01",
"comment_content": "Здравствуйте, Elena!\r\nМы не продавили вам билет, выдавая его за обменный, в то время как он таким не был. Информация о возможностях билета с выбранным тарифом была указана при оформлении. Специалист, который занимался вашим обращением, предоставил вам скриншоты, где показаны условия возврата и обмена при тарифе.\r\nПри оформлении заказа вами были выбраны раздельные билеты двух авиакомпаний: Utair по маршруту Москва — Ереван и Fly One по маршруту Ереван — Дюссельдорф. В таком случае подходящий вам тариф с необходимыми опциями из предлагаемых авиакомпаниями вы выбираете отдельно по каждому билету. По билету Москва — Ереван авиакомпании Utair вы могли выбрать один тариф из трех, предлагаемых авиакомпанией: &quot;Минимум&quot;, &quot;Оптимум&quot; и &quot;Премиум&quot;. Возможность обмена включена авиакомпанией во все три тарифа, но штраф авиакомпании Utair за обмен билета ниже в тарифах &quot;Оптимум&quot; и &quot;Премиум&quot;. Вы выбрали для приобретения тариф &quot;Оптимум&quot;.\r\nДля уточнения возможности получения чека вы можете обратиться в Службу заботы, но для отчётности вы имеете полное право показать посадочные талоны и справку о стоимости.\r\nВладельцем ресурса Kupibilet.ru является компания Nebuchadnezzar FZ-LLC, зарегистрированная на территории ОАЭ. Онлайн-сервис Kupibilet является площадкой, где представлены услуги различных поставщиков на основании соглашения. Иностранная компания не подпадает под действие Федерального закона №54, обязующего организации использовать контрольно-кассовую технику и оформлять чеки. В маршрутной квитанции указана полная стоимость заказа, в том числе и дополнительных услуг. Это, а также выписка по банковской карте, могут являться подтверждением совершенной операции.\r\nЧек предоставляется в случае, если покупка билета осуществляется через компанию Интернет-Билет, зарегистрированную на территории РФ.",
"comment_karma": "0",
"comment_approved": "1",
"comment_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
"comment_type": "comment",
"comment_parent": "60886",
"\u0000*\u0000children": null,
"\u0000*\u0000populated_children": false,
"\u0000*\u0000post_fields": [
"post_author",
"post_date",
"post_date_gmt",
"post_content",
"post_title",
"post_excerpt",
"post_status",
"comment_status",
"ping_status",
"post_name",
"to_ping",
"pinged",
"post_modified",
"post_modified_gmt",
"post_content_filtered",
"post_parent",
"guid",
"menu_order",
"post_type",
"post_mime_type",
"comment_count"
]
},
{
"language_original": "ru_RU",
"comment_rate": "0",
"comment_type": "comment",
"cron_updated": "yes"
}
],
[
{
"comment_post_ID": "81365",
"comment_author": "Августа Конева",
"comment_author_email": "avgusta.koneva@bk.ru",
"comment_author_url": "",
"comment_author_IP": "5.143.205.7",
"comment_date": "2023-05-24 11:28:08",
"comment_date_gmt": "2023-05-24 08:28:08",
"comment_content": "Кресло действительно удобное. Мне так хотелось его купить, но все откладывала и откладывала покупку. Сейчас спина начала с ума сходить, так все таки приобрела его)",
"comment_karma": "0",
"comment_approved": "1",
"comment_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
"comment_type": "comment",
"comment_parent": "60733",
"\u0000*\u0000children": null,
"\u0000*\u0000populated_children": false,
"\u0000*\u0000post_fields": [
"post_author",
"post_date",
"post_date_gmt",
"post_content",
"post_title",
"post_excerpt",
"post_status",
"comment_status",
"ping_status",
"post_name",
"to_ping",
"pinged",
"post_modified",
"post_modified_gmt",
"post_content_filtered",
"post_parent",
"guid",
"menu_order",
"post_type",
"post_mime_type",
"comment_count"
]
},
{
"language_original": "ru_RU",
"comment_rate": "0",
"comment_type": "comment",
"cron_updated": "yes"
}
],
[
{
"comment_post_ID": "238511",
"comment_author": "Иван Петров",
"comment_author_email": "dv@exchangesumo.com",
"comment_author_url": "",
"comment_author_IP": "109.254.170.138",
"comment_date": "2023-05-21 21:11:59",
"comment_date_gmt": "2023-05-21 18:11:59",
"comment_content": "У нас множество обменников с различными направлениями, ждем вас еще у нас на мониторинге. Спасибо за отзыв!",
"comment_karma": "0",
"comment_approved": "1",
"comment_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 YaBrowser/23.5.0.2199 Yowser/2.5 Safari/537.36",
"comment_type": "comment",
"comment_parent": "60415",
"\u0000*\u0000children": null,
"\u0000*\u0000populated_children": false,
"\u0000*\u0000post_fields": [
"post_author",
"post_date",
"post_date_gmt",
"post_content",
"post_title",
"post_excerpt",
"post_status",
"comment_status",
"ping_status",
"post_name",
"to_ping",
"pinged",
"post_modified",
"post_modified_gmt",
"post_content_filtered",
"post_parent",
"guid",
"menu_order",
"post_type",
"post_mime_type",
"comment_count"
]
},
{
"language_original": "ru_RU",
"comment_rate": "0",
"comment_type": "comment",
"cron_updated": "yes",
"comment_translations": [
{
"language": "en_US",
"title": "",
"translation": "We have a lot of exchangers with different directions, we are waiting for you on our monitoring. Thank you for your feedback!",
"pluses": false,
"minuses": false
}
]
}
],
[
{
"comment_post_ID": "238511",
"comment_author": "Иван Петров",
"comment_author_email": "dv@exchangesumo.com",
"comment_author_url": "",
"comment_author_IP": "109.254.170.138",
"comment_date": "2023-05-21 21:11:00",
"comment_date_gmt": "2023-05-21 18:11:00",
"comment_content": "Благодарим за ваше мнение и отзыв.",
"comment_karma": "0",
"comment_approved": "1",
"comment_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 YaBrowser/23.5.0.2199 Yowser/2.5 Safari/537.36",
"comment_type": "comment",
"comment_parent": "60401",
"\u0000*\u0000children": null,
"\u0000*\u0000populated_children": false,
"\u0000*\u0000post_fields": [
"post_author",
"post_date",
"post_date_gmt",
"post_content",
"post_title",
"post_excerpt",
"post_status",
"comment_status",
"ping_status",
"post_name",
"to_ping",
"pinged",
"post_modified",
"post_modified_gmt",
"post_content_filtered",
"post_parent",
"guid",
"menu_order",
"post_type",
"post_mime_type",
"comment_count"
]
},
{
"language_original": "ru_RU",
"comment_rate": "0",
"comment_type": "comment",
"cron_updated": "yes"
}
],
[
{
"comment_post_ID": "238511",
"comment_author": "Иван Петров",
"comment_author_email": "dv@exchangesumo.com",
"comment_author_url": "",
"comment_author_IP": "109.254.170.138",
"comment_date": "2023-05-21 21:10:22",
"comment_date_gmt": "2023-05-21 18:10:22",
"comment_content": "Спасибо за отзыв. Рады, что вам удобен наш сайт.",
"comment_karma": "0",
"comment_approved": "1",
"comment_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 YaBrowser/23.5.0.2199 Yowser/2.5 Safari/537.36",
"comment_type": "comment",
"comment_parent": "60382",
"\u0000*\u0000children": null,
"\u0000*\u0000populated_children": false,
"\u0000*\u0000post_fields": [
"post_author",
"post_date",
"post_date_gmt",
"post_content",
"post_title",
"post_excerpt",
"post_status",
"comment_status",
"ping_status",
"post_name",
"to_ping",
"pinged",
"post_modified",
"post_modified_gmt",
"post_content_filtered",
"post_parent",
"guid",
"menu_order",
"post_type",
"post_mime_type",
"comment_count"
]
},
{
"language_original": "ru_RU",
"comment_rate": "0",
"comment_type": "comment",
"cron_updated": "yes"
}
],
[
{
"comment_post_ID": "238511",
"comment_author": "Иван Петров",
"comment_author_email": "dv@exchangesumo.com",
"comment_author_url": "",
"comment_author_IP": "109.254.170.138",
"comment_date": "2023-05-21 21:09:53",
"comment_date_gmt": "2023-05-21 18:09:53",
"comment_content": "Спасибо за отзыв. Желаем успешных обменов!",
"comment_karma": "0",
"comment_approved": "1",
"comment_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 YaBrowser/23.5.0.2199 Yowser/2.5 Safari/537.36",
"comment_type": "comment",
"comment_parent": "60660",
"\u0000*\u0000children": null,
"\u0000*\u0000populated_children": false,
"\u0000*\u0000post_fields": [
"post_author",
"post_date",
"post_date_gmt",
"post_content",
"post_title",
"post_excerpt",
"post_status",
"comment_status",
"ping_status",
"post_name",
"to_ping",
"pinged",
"post_modified",
"post_modified_gmt",
"post_content_filtered",
"post_parent",
"guid",
"menu_order",
"post_type",
"post_mime_type",
"comment_count"
]
},
{
"language_original": "ru_RU",
"comment_rate": "0",
"comment_type": "comment",
"cron_updated": "yes"
}
]
]